version: '3'

volumes:
  key:

services:
  onion:
    build: .
    image: fphammerle/onion-service
    volumes:
    - key:/onion-service:rw
    environment:
      VIRTUAL_PORT: 80
      TARGET: 1.2.3.4:8080
    security_opt: [no-new-privileges]
    restart: unless-stopped

# https://docs.docker.com/compose/compose-file/
